services:
  repoinsight-server:
    image: ${IMAGE_NAME}
    ports:
      - "8000:8000"
    depends_on:
      redis-cache:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis-cache:6379/0
      - OPENAI_API_KEY
      - PINECONE_API_KEY
      - GIT_API_TOKEN
      - FRONTEND_URL

  redis-cache:
    image: redis:7.4-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 10